import Head from "next/head";
import Coins from "../components/Coins";
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home({ coins }) {
  // console.log(coins);
  const coinsData = coins.data;
  // console.log(coinsData);

  return (
    <div className="bg-gray-100">
      <Head>
        <title>Market overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-10 ">
        {/* Front Header Section */}
        <div className=" flex flex-col items-center py-40">
          <h2 className="text-5xl font-bold py-2 ">
            Top Coins
          </h2>
          <p className="text-xl font-medium">
            Market overview
          </p>
        </div>
        <div className="my-20">
          <Coins coinsData={coinsData} />
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const coins = await fetch(
    "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest",
    {
      method: "GET",
      headers: { "X-CMC_PRO_API_KEY": "c7a44651-6ef7-4079-a18a-6c6ded2cc9a7" },
    }
  ).then((res) => res.json());

  return {
    props: { coins },
  };
}
